### ISSUE TITLE
Remove need for `aioredis` if redis-py is 4.2+

### ISSUE THREAD

**Issue by cunla** [dsoftwareinc/fakeredis-py#13]
**Is your feature request related to a problem? Please describe.**
Aioredis is now in redis-py 4.2.0rc1+ as described [here](https://github.com/aio-libs/aioredis-py)

**Describe the solution you'd like**
Default should be not requiring aioredis.

**Comment by ikornaselur** [comment]
Are there other changes required than introduced by #10?

**Comment by ikornaselur** [comment]
Fair enough, that should only require the similar logic as there is already in place (for aioredis v1 vs v2), right? I'd be happy to make a PR for this 🙏

**Comment by cunla** [comment]
> Fair enough, that should only require the similar logic as there is already in place (for aioredis v1 vs v2), right? I'd be happy to make a PR for this 🙏
> 
> Edit:
> 
> Just looking into this and have few questions:
> 
> * Is there any reason to depend on `aioredis` at all? The project depends on redis `4.3.1`, so there shouldn't be a need to check for the version at all, right? Unless the minimum redis version would be below 4.2.

It is possible to use redis below 4.2 with fakeredis - see the actions tab with various options I am testing.
So aioredis should be optional dependency, like lupa.

> * I do have a version running locally that works (tested by manually `poetry run pip install redis==4.1` to verify that it does fallback to `aioredis`), what would be a good way to test this behaviour, if required?

You can tell whether `aioredis` is used or `redis.asyncio` is used by using something that only `aioredis` will have. Something like:
```
is_aioredis_used = hasattr(aioredis, '__version__') 
```
I would like to test 4 scenarios:
1. redis>=4.2 (redis==4.3.1) without aioredis ==> should work fine with redis.asyncio
2. redis>=4.2 (redis==4.3.1) and aioredis==2.0.1 ==> ensure aioredis is not used
3. redis<4.2 (redis==4.1) and aioredis==2.0.1 ==> Already exists
4. redis<4.2 (redis==4.1) and aioredis==1.3.1 ==> Already exists
5. redis<4.2 (redis==4.1) without aioredis ==> should output a proper error.


> 
> I'm not too well versed in shipping libraries like this, so I would love to learn if there are contexts where `redis` could be below 4.2 with the latest version of `fakeredis-py`.

fakeredis does not require redis to be latest, so it is possible.

**Comment by ikornaselur** [comment]
Thanks for all the info! This might potentially be more than I anticipated, but I might take a crack at it tonight. Don't feel like you need to wait for me to submit anything though, as if I don't find time tonight I won't have time until the weekend :pray: 

I just have couple of follow up questions:

 > So aioredis should be optional dependency, like lupa.

I see that in #12 you migrated to poetry, where before you did have `lupa` and `aioredis` as optional in your `setup.cfg`:

```
[options.extras_require]
lua =
    lupa
aioredis =
    aioredis
```

but it doesn't seem to be the case in the `pyproject.toml` today with Poetry, unless there is some different way that I'm not aware of to mark them as optional. [As per the poetry documentation](https://python-poetry.org/docs/pyproject/#extras) that's how extras are 'expected' to be defined at least - if there's a different way it's specified in this project then I'd love to learn about that.

> fakeredis does not require redis to be latest, so it is possible.

I also see that in the `setup.cfg` removed in #12 it does say

```
install_requires =
    ...
    redis<=4.3.1
```
which matches what I see in a project that uses fakeredis

```
❯ poetry show fakeredis
name         : fakeredis
version      : 1.7.5
description  : Fake implementation of redis API for testing purposes.

dependencies
 - packaging *
 - redis <=4.3.1
 - six >=1.12
 - sortedcontainers *
```

but with the move to poetry, I'm only seeing a ping to `4.3.1` in pyproject.toml, so similar to the previous question, are you specifying the optional and more lenient requirements somewhere else now?
