### ISSUE TITLE
1.8 does not work as a monkey patch

### ISSUE THREAD

**Issue by PeteDouma** [dsoftwareinc/fakeredis-py#29]
I was using version 1.7.1 and this code worked

```
import redis
import arrow
import fakeredis

from datetime import date


def test_state(monkeypatch):
    monkeypatch.setattr(redis,'Redis',fakeredis.FakeRedis )

    from ..src.status import SystemState
    state = SystemState()

    print(state.serial)
    assert state.version == '2.0'
    assert state.timezone == 'America/New_York'
    state.lights = 'off'
    value, when = state.lights
    assert value == 'off'
 
```

However in 1.8 I get a connection pool error

**Comment by cunla** [comment]
Can you mention python version, dependencies, and stacktrace?

**Comment by PeteDouma** [comment]
python version 3.9 on a Raspberry Pi Zero
Version 1.81
`src/status.py:16: in __init__
    self.redis = redis.Redis(decode_responses=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[AttributeError("'FakeRedis' object has no attribute 'connection_pool'") raised in repr()] FakeRedis object at 0x751f8d48>, server = None, connected = True, args = ()
kwargs = {'decode_responses': True}
default_args = odict_values([<Parameter "self">, <Parameter "*args">, <Parameter "server=None">, <Parameter "connected=True">, <Parameter "**kwargs">])
kwds = {'connected': True, 'decode_responses': True, 'server': None}

    def __init__(self, *args, server=None, connected=True, **kwargs):
        # Interpret the positional and keyword arguments according to the
        # version of redis in use.
        default_args = inspect.signature(redis.Redis.__init__).parameters.values()
        kwds = {p.name: p.default for p in default_args if p.default != inspect._empty}
        kwds.update(kwargs)
        # bound = _ORIG_SIG.bind(*args, **params)
        # kwds = bound.arguments['kwds']
>       if not kwds['connection_pool']:
E       KeyError: 'connection_pool'

../../../lib/python3.9/site-packages/fakeredis/_server.py:2825: KeyError`

**Comment by PeteDouma** [comment]
Thanks
