### ISSUE TITLE
lmove operation is missing

### ISSUE THREAD

**Issue by BGroever** [dsoftwareinc/fakeredis-py#7]
lmove operation is a new feature in redis version 6.2.0
It is similar to RPOPLPUSH, but instead it always poping and pushing from both side of the list independently
I am happy to implement it myself, I already have started a branch for this if you give me permission to do so

**Comment by cunla** [comment]
Sounds good to me. No need for my permission :) you can fork and create a PR.
Make sure to also include a test for it.

**Comment by BGroever** [comment]
@cunla do you know when you will ship the next version?
